name: Build MkDocs site

on:
  push:
    branches:
      - main

permissions:
  contents: write   # ✅ allows pushing back to repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install mkdocs

      - name: Build MkDocs
        run: mkdocs build --config-file mkdocs_src/mkdocs.yml

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --cached --quiet || git commit -m "Update docs [skip ci]"
          git push
