name: Build MkDocs site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs
      - run: mkdocs build --config-file mkdocs_src/mkdocs.yml
      - run: git add docs && git commit -m "Update docs [skip ci]" || echo "No changes"
      - run: git push
